[package]
name = "no-std"
version = "0.1.0"
edition = "2021"

[dependencies]
rlsf = "0.2"

[dependencies.pasts]
version = "0.14"
default-features = false

[dependencies.whisk]
version = "0.12"
features = ["pasts"]
